import puppeteer from "puppeteer";

const esc = (value: unknown) => String(value ?? "")
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;")
  .replace(/'/g, "&#039;");

const money = (value: unknown, currency: string) => `${Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
const date = (value: unknown) => value ? new Date(value as any).toLocaleDateString("en-GB", { year: "numeric", month: "short", day: "2-digit" }) : "—";

function shell(title: string, body: string) {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;color:#0f172a;margin:0;padding:0;font-size:12px}
  .page{padding:34px}.top{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #0f172a;padding-bottom:20px;margin-bottom:24px}
  .brand{font-size:22px;font-weight:800;letter-spacing:-.4px}.muted{color:#64748b}.title{text-transform:uppercase;font-size:10px;letter-spacing:2px;font-weight:800;color:#2563eb;margin-bottom:6px}
  h1{font-size:24px;margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:20px 0}.box{border:1px solid #e2e8f0;border-radius:10px;padding:14px}
  table{width:100%;border-collapse:collapse;margin-top:22px}th{text-align:left;color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:.8px;padding:9px;border-bottom:1px solid #cbd5e1}td{padding:10px 9px;border-bottom:1px solid #e2e8f0}
  .right{text-align:right}.total{font-weight:800;font-size:14px}.footer{margin-top:30px;border-top:1px solid #e2e8f0;padding-top:12px;color:#94a3b8;font-size:10px}
  .status{display:inline-block;border-radius:999px;background:#ecfdf5;color:#047857;font-weight:800;font-size:10px;padding:5px 9px;text-transform:uppercase}
</style>
</head><body><div class="page">${body}<div class="footer">Generated by Blih ERP · ${esc(new Date().toISOString())}</div></div></body></html>`;
}

export async function generateSubscriptionInvoicePdf(input: { business: any; subscription: any; invoice: any; payments: any[] }) {
  const { business, subscription, invoice, payments } = input;
  const currency = invoice.currency || "ETB";
  const paid = payments.filter((p) => p.status === "paid").reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const outstanding = Math.max(0, Number(invoice.totalAmount || 0) - paid);
  const html = shell("Subscription invoice", `
    <div class="top"><div><div class="brand">Blih ERP</div><div class="muted">Subscription billing</div></div><div class="right"><div class="title">Invoice</div><h1>${esc(invoice.invoiceNumber)}</h1><div style="margin-top:8px"><span class="status">${esc(invoice.status)}</span></div></div></div>
    <div class="grid">
      <div class="box"><div class="title">Bill to</div><strong>${esc(business.name)}</strong><div class="muted" style="margin-top:5px">${esc(business.email || "")}</div><div class="muted">${esc(business.phone || "")}</div></div>
      <div class="box"><div class="title">Billing details</div><div>Plan: <strong>${esc(subscription.Plan?.name || subscription.planId)}</strong></div><div style="margin-top:5px">Period: ${date(invoice.periodStart)} — ${date(invoice.periodEnd)}</div><div style="margin-top:5px">Due: ${date(invoice.dueDate)}</div></div>
    </div>
    <table><thead><tr><th>Description</th><th class="right">Amount</th></tr></thead><tbody>
      <tr><td>Base subscription</td><td class="right">${money(invoice.baseAmount, currency)}</td></tr>
      <tr><td>Extra seats</td><td class="right">${money(invoice.seatAmount, currency)}</td></tr>
      <tr><td>Metered usage</td><td class="right">${money(invoice.usageAmount, currency)}</td></tr>
      <tr><td>Discount</td><td class="right">− ${money(invoice.discountAmount, currency)}</td></tr>
      <tr><td>Tax</td><td class="right">${money(invoice.taxAmount, currency)}</td></tr>
      <tr><td class="total">Total</td><td class="right total">${money(invoice.totalAmount, currency)}</td></tr>
      <tr><td>Paid</td><td class="right">${money(paid, currency)}</td></tr>
      <tr><td class="total">Outstanding</td><td class="right total">${money(outstanding, currency)}</td></tr>
    </tbody></table>
  `);
  return renderPdf(html);
}

export async function generateSubscriptionPaymentReceiptPdf(input: { business: any; invoice: any; payment: any }) {
  const { business, invoice, payment } = input;
  const currency = payment.currency || invoice.currency || "ETB";
  const html = shell("Payment receipt", `
    <div class="top"><div><div class="brand">Blih ERP</div><div class="muted">Subscription billing</div></div><div class="right"><div class="title">Payment receipt</div><h1>${esc(payment.providerReference || payment.id.slice(0, 8).toUpperCase())}</h1><div style="margin-top:8px"><span class="status">${esc(payment.status)}</span></div></div></div>
    <div class="grid">
      <div class="box"><div class="title">Received from</div><strong>${esc(business.name)}</strong><div class="muted" style="margin-top:5px">${esc(business.email || "")}</div></div>
      <div class="box"><div class="title">Payment</div><div>Invoice: <strong>${esc(invoice.invoiceNumber)}</strong></div><div style="margin-top:5px">Paid: ${date(payment.paidAt)}</div><div style="margin-top:5px">Method: ${esc(payment.provider)}</div></div>
    </div>
    <table><thead><tr><th>Description</th><th class="right">Amount</th></tr></thead><tbody>
      <tr><td>Subscription payment</td><td class="right total">${money(payment.amount, currency)}</td></tr>
    </tbody></table>
    ${payment.metadata?.notes ? `<div class="box" style="margin-top:22px"><div class="title">Notes</div>${esc(payment.metadata.notes)}</div>` : ""}
  `);
  return renderPdf(html);
}

async function renderPdf(html: string): Promise<Buffer> {
  const browser = await puppeteer.launch({ headless: true, args: ["--no-sandbox", "--disable-setuid-sandbox"] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" } as any);
    const pdf = await page.pdf({ format: "A4", printBackground: true, margin: { top: "12mm", right: "12mm", bottom: "12mm", left: "12mm" } });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
